---
name: GSG
version: 0.5
slug: gsg
description: Un add-on pour gérer un stock de sacs de granulés de bois
url: https://github.com/antibill51/gsg-addon
codenotary: remi.kiragossian@gmail.com
webui: "[PROTO:ssl]://[HOST]:[PORT:9541]"
startup: services
init: false
ingress: true
ingress_port: 9541
ingress_entry: /
panel_icon: "mdi:fire"
panel_title: "Stock Granulés"
panel_admin: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  9541/tcp: 9541
ports_description:
  9541/tcp: GSG web interface
options:
  mysql_host: core-mariadb
  mysql_user: gsg
  mysql_password: gsg
  mysql_database: gsg
schema:
  mysql_host: str
  mysql_user: str
  mysql_password: password
  mysql_database: str
